### PR TITLE
Add user roles in activities

### PR DESCRIPTION
**Pull request by mariuscoto**

### CODE REVIEW

**Comment by mariuscoto** [comment]
TODO:
* individual pages for each event
* user /activities/ACTIVITY_NAME/EDITION_NAME to access editon info
* list events on editon page
* replace IDs on profile page with actual names
* allow only members to add activities, events and roles

**Comment by mariuscoto** [comment]
@maria please review UI/UX so we can beta-test it and gather data

**Comment by mariuscoto** [comment]
@fullvlad please have a look

**Comment by maria** [comment]
1. The form looks not that good: 
screenshot 2015-05-09 10 36 05

Some spaces are missing..and the style is not similar with other forms.

2. The list of people involved is also badly formatted

screenshot 2015-05-09 10 38 33

The link to ones profile doesn't appear on the activity page only on the event page.

3. There is the `Add new edition` form always inserted in the page.
4. There is no way of adding new organisers without setting the edition name and period.
5. There is no form to add a new Event on the Edition page.

GG :+1:

**Pull request merged**
